version: '3.8'

services:
  # MarketSage Admin Portal - Staff management interface
  marketsage-admin:
    container_name: marketsage-admin
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-production}
    ports:
      - "${ADMIN_PORT:-3001}:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001

      # Authentication
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3001}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

      # Backend API connection
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://localhost:3006}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}

      # Sentry monitoring (optional)
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN:-}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN:-}
      - SENTRY_ORG=${SENTRY_ORG:-}
      - SENTRY_PROJECT=${SENTRY_PROJECT:-}

      # Admin-specific settings
      - NEXT_PUBLIC_ADMIN_EMAIL=${NEXT_PUBLIC_ADMIN_EMAIL:-admin@marketsage.com}
      - NEXT_PUBLIC_SUPPORT_EMAIL=${NEXT_PUBLIC_SUPPORT_EMAIL:-support@marketsage.com}

    networks:
      - marketsage-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:3001/api/health || wget --no-verbose --tries=1 --spider http://localhost:3001/api/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    profiles:
      - admin
      - all
    depends_on:
      - marketsage-backend

  # Backend API service (reference - should be running separately)
  marketsage-backend:
    image: marketsage-backend:latest
    container_name: marketsage-backend
    ports:
      - "${BACKEND_PORT:-3006}:3006"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3006
    networks:
      - marketsage-network
    restart: unless-stopped
    profiles:
      - backend
      - all

  # Nginx reverse proxy (optional for production)
  nginx:
    image: nginx:alpine
    container_name: marketsage-admin-nginx
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - marketsage-admin
    networks:
      - marketsage-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - proxy
      - production

networks:
  marketsage-network:
    driver: bridge
    name: marketsage_admin_${NODE_ENV:-development}
    ipam:
      config:
        - subnet: 172.21.0.0/16
